# Generated by Django 2.2 on 2020-11-13 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_friends', '0003_auto_20201113_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.AddField(
            model_name='friend',
            name='other',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='app_friends.User'),
            preserve_default=False,
        ),
    ]
