# Generated by Django 2.2 on 2020-11-13 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_friends', '0004_auto_20201113_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='other',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='friend',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='app_friends.User'),
        ),
        migrations.AddField(
            model_name='friend',
            name='users',
            field=models.ManyToManyField(to='app_friends.User'),
        ),
    ]
