# Generated by Django 2.2 on 2020-11-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_friends', '0005_auto_20201113_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='users',
            field=models.ManyToManyField(related_name='friend', to='app_friends.User'),
        ),
    ]
