# Generated by Django 2.2 on 2020-11-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_friends', '0006_auto_20201113_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='app_friends.User'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
